# Generated by Django 5.2.5 on 2025-08-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='attentionsample',
            options={'ordering': ['-created_at']},
        ),
    ]
