# Generated by Django 5.2.5 on 2025-08-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancesession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_activity', models.PositiveIntegerField(default=70)),
                ('pct_attention', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
