# Generated by Django 5.2.5 on 2025-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentionsample',
            name='absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attentionsample',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='attentionsample',
            name='ear',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attentionsample',
            name='mar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attentionsample',
            name='yaw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
