# Generated by Django 5.2.5 on 2025-08-13 03:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_enrollment_options_enrollment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='post_type',
            field=models.CharField(choices=[('evaluacion', 'Evaluación'), ('tarea', 'Tarea')], default='tarea', max_length=12),
        ),
        migrations.AddField(
            model_name='activity',
            name='requires_monitoring',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ActivityAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('monitoring_score', models.FloatField(default=0.0)),
                ('evaluation_grade', models.FloatField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.activity')),
                ('monitoring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_attempts', to='core.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_attempts', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='core.submission')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['activity', 'student'], name='core_activi_activit_4aa375_idx')],
            },
        ),
    ]
