# Generated by Django 5.2.5 on 2025-08-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evaluation_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='evaluatio_seq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='exam_mode',
            field=models.CharField(blank=True, choices=[('quiz', 'quiz'), ('file', 'file')], default='quiz', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_evaluatio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='learning_type',
            field=models.CharField(blank=True, choices=[('video', 'video'), ('pdf', 'pdf'), ('clase', 'clase'), ('otro', 'otro')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='learning_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_evaluatio', True)), fields=('module', 'evaluatio_seq'), name='uq_activity_module_evaluatioseq'),
        ),
    ]
