web: cd backend && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:$PORT
python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:$PORT
Set-Content -NoNewline -Path Procfile -Value "web: python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:`$PORT"
